name: ci

on: [ push ]

jobs:
  build_containers:
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: 'build_containers_v${{ matrix.config.version }}'

    strategy:
      fail-fast: false
      matrix:
        config:
          - {version: '1.0.0', latest: ''}
          - {version: '1.0.1', latest: ''}
          - {version: '1.1.0', latest: ''}
          - {version: '1.2.0', latest: ''}
          - {version: '1.2.1', latest: ''}
          - {version: '1.3.0', latest: ''}
          - {version: '1.3.1', latest: ',ghcr.io/data-intuitive/dotnet-script:latest'}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test container
        run: ./test.sh ${{ matrix.config.version }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GTHB_USER }}
          password: ${{ secrets.GTHB_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/data-intuitive/dotnet-script:${{ matrix.config.version }}${{ matrix.config.latest }}
          build-args: |
            DNV=${{ matrix.config.version }}